name: live2text CI_3

on:
  push:
    branches:
      - 'main'
  pull_request:
    tags:
      - 'v*'
    branches-ignore:
      - 'feature/*'

env:
  GOLANG_VERSION: '1.24.3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '^1.24.3'

      - name: Print Go version
        run: go version

