name: live2text CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  GOLANG_VERSION: '1.24.5'

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: "^${{ env.GOLANG_VERSION }}"

      - name: Install Linux dependencies (gcc, portaudio)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential portaudio19-dev

      - name: Build live2text
        run: go build -v ./cmd/live2text

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: "^${{ env.GOLANG_VERSION }}"

      - name: Install Linux dependencies (gcc, portaudio)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential portaudio19-dev

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Run tests with coverage
        run: go test ./... -coverprofile=coverage.out -covermode=atomic

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: "^${{ env.GOLANG_VERSION }}"

      - name: Install Linux dependencies (gcc, portaudio)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential portaudio19-dev

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

      - name: Run golangci-lint
        run: golangci-lint run --config .golangci.yml