name: live2text CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  GOLANG_VERSION: '1.24.3'
  ACTIONS_STEP_DEBUG: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: "^${{ env.GOLANG_VERSION }}"

      - name: Print Go version
        run: | 
          go version
          echo "GOLANG_VERSION: $GOLANG_VERSION"
          echo "github: ${{ toJSON(github) }}"
          echo "env: ${{ toJSON(env) }}"
          echo "secrets: ${{ toJSON(secrets) }}"
          echo "job: ${{ toJSON(job) }}"
          echo "steps: ${{ toJSON(steps) }}"
          echo "runner: ${{ toJSON(runner) }}"
          echo "matrix: ${{ toJSON(matrix) }}"
          echo "inputs: ${{ toJSON(inputs) }}"

